### ISSUE TITLE
Build SQL Database Schema

### ISSUE THREAD

**Issue by aplai168** [1Body/prayer-app#2]

**Comment by nteal** [comment]
We finished the "schema" the same night we video called, right?

**Comment by nteal** [comment]
![prayerAppDataBaseShcema.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5954629368d108001ab42e25/125516c66e82c728ace21e0d46f8869b3a8791889ff99b42b05cd2953a43147b2a01ae2a32c9a138ad4d71040c1b5ca6535d5641f8ff8b7aa4b03e76dc550cedd16c0e27c63510afb89003ad43eb7edf10d8eff6df0ed2e22f26e6818e4b3717011d8ffd5f3ca39f4eda15.png)
